#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC2086
umask 022
command="/app/tdrive/uploader.sh"
sleep 10
echo "-> Starting tdrive Uploader <-"
exec s6-setuidgid abc $command
