#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC2086
umask 022
serverside_command="/app/serverside/serverside.sh"
sleep 3
echo "-> Starting Server-Side Uploader <-"
exec s6-setuidgid abc $serverside_command
