#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[UPLOADER] ${1}"
}

addgroup -g 911 abc
adduser -u 911 -D -G abc abc

apk add --quiet --no-cache --no-progress wget curl bash unzip
curl --quiet -O https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
unzip rclone-current-linux-amd64.zip -C /usr/bin/ && \
rm -f rclone-current-linux-amd64.zip 

log "**** update system ****" 
apk --quiet --no-cache --no-progress update
log "**** install build packages ****"
apk add --quiet --no-cache --no-progress \
    ca-certificates logrotate shadow bash bc findutils coreutils openssl php7 php7-fpm php7-mysqli php7-json php7-openssl \
    php7-curl php7-zlib php7-xml php7-phar php7-dom php7-xmlreader php7-ctype php7-mbstring php7-gd \
    curl nginx libxml2-utils tzdata openntpd grep tar
log "**** upgrade system ****"
apk --quiet --no-cache --no-progress upgrade
apk --quiet --no-progress --no-cache fix
apk del --quiet --clean-protected --no-progress
rm -rf /var/cache/apk/*

rm -rf /etc/nginx/nginx.conf && cp -rv /conf/nginx.conf /etc/nginx/nginx.conf
cp -rv /conf/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
cp -rv /conf/php.j2 /etc/php7/conf.d/zzz_custom.ini

pids="$(pgrep 'nginx')"
if [ "$pids" != "" ]; then
  kill -15 $pids
  sleep 2
fi

#EOF#