#!/usr/bin/with-contenv bash
# shellcheck shell=bash

TARGET_FOLDER='/etc/services.d/{uploader-gdrive,uploader-tdrive,serverside,cleaning}'
FIND=$(which find)
FIND_BASE='-type f'
FIND_FILE='"down"'
FIND_FILE_ACTION='-name'
FIND_MINDEPTH='-mindepth 1'
FIND_ACTION='-delete 1>/dev/null 2>&1'
command="${FIND} ${TARGET_FOLDER} ${FIND_MINDEPTH} ${FIND_FILE_ACTION} ${FIND_FILE} ${FIND_BASE} ${FIND_ACTION}"
eval ${command}
rjson=/config/rclone/rclone-docker.conf
if grep -q GDSA01C "${rjson}" && grep -q GDSA02C "${rjson}"; then
    echo "-->> -------------------- <<--"
    echo "-->    TCRYPT UPLOADER    <<--"
    echo "-->       WILL USED       <<--"
    echo "-->> -------------------- <<--"
else
    echo "-->> -------------------- <<--"
    echo "-->    TDRIVE UPLOADER    <<--"
    echo "-->       WILL USED       <<--"
    echo "-->> -------------------- <<--"
    exit 0
fi
#<EOF>#
