#!/usr/bin/with-contenv bash
# shellcheck shell=bash
## function source end
UAGENT=${UAGENT:-null}
if [[ ${UAGENT} == 'null' ]];then
   UAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
   USERAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
else
   UAGENT=${UAGENT}
   USERAGENT=${USERAGENT}
fi

uploaderenv=/config/env/uploader.env
if [[ ! -f "${uploaderenv}" ]]; then
echo -e "BANDWITHLIMIT=${BWLIMITSET:-40M}
ADDITIONAL_IGNORES=${ADDITIONAL_IGNORES:-null}
TRANSFERS=${TRANSFERS:-4}
USERAGENT=${USERAGENT}
TZ=${TZ:-UTC}
CLEANUPDOWN=${CLEANUPDOWN:-null}
CAPACITY_LIMIT=${CAPACITY_LIMIT:-null}
LOGHOLDUI=${LOGHOLDUI:-5m}
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-null}
DISCORD_EMBED_TITEL=${DISCORD_EMBED_TITEL:-UPLOADED_COMPLETE}
DISCORD_ICON_OVERRIDE=${DISCORD_ICON_OVERRIDE:-https://i.imgur.com/MZYwA1I.png}
DISCORD_NAME_OVERRIDE=${DISCORD_NAME_OVERRIDE:-UPLOADED}" >> /config/env/uploader.env
else
  echo "-->> -------------------- <<--"
  echo "     --> used stored <--  <<--"
  echo "          env files       <<--"
  echo "-->> -------------------- <<--"
fi

serversideenv=/config/env/serverside.env
if [[ ! -f "${serversideenv}" ]]; then
echo -e "SERVERSIDE=${SERVERSIDE:-false}
SERVERSIDEDAY=${SERVERSIDEDAY:-Sunday}
SERVERSIDEMINAGE=${SERVERSIDEMINAGE:-null}
SERVERSIDEDRIVE=${SERVERSIDEDRIVE:-null}
REMOTEDRIVE=${REMOTEDRIVE:-null}
DISCORD_WEBHOOK_URL_SERVERSIDE=${DISCORD_WEBHOOK_URL_SERVERSIDE:-null}
DISCORD_EMBED_TITEL_SERVERSIDE=${DISCORD_EMBED_TITEL_SERVERSIDE:-Server-Side-Move}
DISCORD_ICON_OVERRIDE_SERVERSIDE=${DISCORD_ICON_OVERRIDE_SERVERSIDE:-https://i.imgur.com/MZYwA1I.png}
DISCORD_NAME_OVERRIDE_SERVERSIDE=${DISCORD_NAME_OVERRIDE_SERVERSIDE:-Server-Side}" >> /config/env/serverside.env 
else
  echo "-->> -------------------- <<--"
  echo "     --> used stored <--  <<--"
  echo "       serverside.env     <<--"
  echo "-->> -------------------- <<--"
fi

#while read -r line; do declare -x "$line"; done < <(egrep -v "(^#|^\s|^$)" /config/env/serverside.env)
#while read -r line; do declare -x "$line"; done < <(egrep -v "(^#|^\s|^$)" /config/env/uploader.env)

if [ "${CLEANUPDOWN}" == 'down' ] || [ "${CLEANUPDOWN}" == 'false' ]; then
   touch /etc/services.d/cleaning/down
   echo " [ USER WISH ACTION ] "
   echo "   Shutdown Cleaning  "
   echo " [ USER WISH ACTION ] "
   sleep 10
else 
   echo " [ USER WISH ACTION ] "
   echo "   Starting Cleaning  "
   echo " [ USER WISH ACTION ] "
   sleep 5
fi
#<EOF>#
