#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Uploader] ${1}"
}
log "-> update packages || start <-" 
apk --no-cache update --quiet 
apk --no-cache upgrade --quiet
apk --no-cache fix --quiet
apk del --quiet --clean-protected --no-progress
echo "@weekly bash /app/update-alpine/update-alpine.sh" > /tmp/crontab.conf
crontab /tmp/crontab.conf
rm -rf /var/cache/apk/*
log "-> update packages || done <-"
sleep 2
#>EOF<#
