#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Uploader] ${1}"
}
log "-> install vnstat || start <-"
apk add --quiet --no-cache --no-progress vnstat
rm -rf /var/cache/apk/*
vnstat --add -i eth0 1>/dev/null 2>&1
sed -i '/Interface/s/""/"eth0"/' /etc/vnstat.conf
sed -i '/UseLogging/s/2/0/' /etc/vnstat.conf
sed -i '/RateUnit/s/1/0/' /etc/vnstat.conf
sed -i '/UnitMode/s/0/1/' /etc/vnstat.conf
vnstat --remove -i eth1 --force 1>/dev/null 2>&1
vnstat -i eth0 1>/dev/null 2>&1
log "-> create vnstat database || done <-"
chown -R vnstat:vnstat /var/lib/vnstat/
log "-> install vnstat || done <-"
