#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
    echo "[Server Side] ${1}"
}
source /config/env/serverside.env
RCLONEDOCKER=/config/rclone/rclone.conf
SERVERSIDE=${SERVERSIDE}

if [[ "${SERVERSIDE}" != 'true' ]]; then
   log "-> Server_side skipped <- "
   touch /etc/services.d/serverside/down
else
   log "-> Server_side will be used <-"
fi
#EOF
